name: Generate Snake

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *"   # runs daily at midnight UTC
  workflow_dispatch:      # allows manual run

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: monikabaabu
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-pink.svg?color_snake=#9d174d&color_dots=#1a1a1a,#7A0E4E,#9E1364,#C2187A,#E91E8D,#FF2E95,#FF4FA6,#FF73B8,#FF9ACB,#FFC1DE,#FFE6F2


      - name: Publish snake animation
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
