name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate snake (dark pink)
        uses: Platane/snk@v2
        with:
          github_user_name: monikabaabu
          outputs: |
            dist/github-contribution-grid-snake-pink.svg
          snake_color: "#db2777"
          color_dots: |
            #f472b6
            #ec4899
            #db2777
            #be185d
            #9d174d

      - name: Push snake
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
